apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s-sample
spec:
  selector:
    matchLabels:
      app: spring-k8s-sample
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-k8s-sample
    spec:
      containers:
        - name: spring-k8s-sample
          image: mastanvali2600/springk8ssample:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
