kind: Service
apiVersion: v1
metadata:
  name: spring-k8s-sample
spec:
  selector:
    app: spring-k8s-sample
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
